name: Documentation

permissions:
  contents: read

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # Every Monday at 08:00 UTC
    - cron: '0 8 * * 1'

env:
  CARGO_TERM_COLOR: always
  # Treat all warnings as errors to ensure high-quality documentation
  RUSTDOCFLAGS: -D warnings

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Build documentation
      run: cargo doc --workspace --exclude llguidance_py --no-deps --all-features --locked

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v7
      with:
        name: documentation
        path: target/doc/
